#!/usr/bin/env python3
"""Freshness/liveness overclaim check for the dwelling companion site.

dashboard.html advertised itself as live and named an update mechanism that
does not exist: the meta description said "Live state dashboard", the index
link said "Dashboard — live state, open PRs, dream fragments", and the footer
said the page was "Updated when the dwelling companion is rebuilt". Nothing
regenerates that page -- `git log -- dashboard.html` returns two commits, both
dated 2026-06-24 -- while the site itself IS rebuilt on every push to master,
so the rebuild happens and the snapshot does not change.

This checks the whole CLAIM CLASS: CONSTRUCTIONS that assert a page reflects
CURRENT state (now, at the moment you read it) or is refreshed AUTOMATICALLY
by some process. A grep for one wording of that overclaim misses the same
claim phrased differently, and the fix for one page is not a fix for the class.

The patterns below target those constructions, never the bare word "live".
"live" on this site also names an honest in-the-moment interactive FEATURE:
breathing-circle-live.html is a client-side page (its script runs in the
reader's browser, and its status text reads 'live — seed data'), and the index
link "Breathing circle — live calibration" describes that page, not a promise
that anything is being kept current. Likewise stillness-profile.html's "The
radar chart updates live" describes a chart the reader's own browser redraws.
"live calibration", "live circle" and bare "updates live" are honest and must
stay unflagged, so do not add them here. If breathing-circle-live.html ever
makes a genuine freshness claim, add that construct specifically -- never the
bare word "live".

The honest replacement wording on dashboard.html -- a dated snapshot, typed by
hand, not regenerated by any build -- is the negative control: it must stay
green.

Run from the repo root:  python3 check_freshness.py [path]
    path may be a single .html file or a directory (default: ".").
Exit 0 if clean, 1 if any freshness overclaim found.
"""
import sys
from pathlib import Path

# The freshness/liveness overclaim phrasing class, case-insensitive. Keep this
# list auditable and explicit: every entry is a construction, not a topic word.
PATTERNS = [
    "live state",
    "live dashboard",
    "live data",
    "real-time",
    "real time",
    "updated automatically",
    "automatically updated",
    "updated when the",
    "always current",
    "always up to date",
    "up to the minute",
    "up-to-the-minute",
]


def html_files(root):
    """Return the .html files to scan for a file or directory target."""
    p = Path(root)
    if p.is_file():
        return [p] if p.suffix.lower() == ".html" else []
    return sorted(q for q in p.rglob("*.html") if ".git" not in q.parts)


def main(argv):
    target = argv[1] if len(argv) > 1 else "."
    files = html_files(target)
    hits = []
    for f in files:
        text = f.read_text(errors="replace")
        for lineno, line in enumerate(text.splitlines(), 1):
            low = line.lower()
            for pat in PATTERNS:
                if pat in low:
                    hits.append(f"{f}:{lineno}: {pat}")
    for h in hits:
        print(h)
    print(f"files scanned: {len(files)}  hits found: {len(hits)}")
    return 1 if hits else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
